Ruby_Assignments/Day_11/blog/config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  post 'auth_user' => 'authentication#authenticate_user'

  root "articles#index"

  resources :articles
end

Ruby_Assignments/Day_11/blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Ruby_Assignments/Day_11/blog/app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

Ruby_Assignments/Day_11/blog/app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

Ruby_Assignments/Day_11/blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  attr_reader :current_model

  protected
  def authenticate_request!
    unless model_id_in_token?
      render json: { errors: ['Not Authenticated'] }, status: :unauthorized
      return
    end
    @current_model = Model.find(auth_token[:model_id])
  rescue JWT::VerificationError, JWT::DecodeError
    render json: { errors: ['Not Authenticated'] }, status: :unauthorized
end

private
 def http_token
     @http_token ||= if request.headers['Authorization'].present?
       request.headers['Authorization'].split(' ').last
     end
 end

 def auth_token
   @auth_token ||= JsonWebToken.decode(http_token)
 end

 def model_id_in_token?
   http_token && auth_token && auth_token[:model_id].to_i
 end
end

Ruby_Assignments/Day_11/blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  before_action :authenticate_request!

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
  @article = Article.find(params[:id])
  @article.destroy

  redirect_to root_path, status: :see_other
  end

  private
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

Ruby_Assignments/Day_11/blog/app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  def authenticate_user
    model = Model.find_for_database_authentication(email: params[:email])
    if model.valid_password?(params[:password])
      render json: payload(model)
    else
      render json: {errors: ['Invalid Username/Password']}, status: :unauthorized
    end
  end

  private

  def payload(model)
    return nil unless model and model.id
    {
      auth_token: JsonWebToken.encode({model_id: model.id}),
      model: {id: model.id, email: model.email}
    }
  end
end

Ruby_Assignments/Day_11/blog/app/helpers/application_helper.rb
module ApplicationHelper
end

Ruby_Assignments/Day_11/blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

Ruby_Assignments/Day_11/blog/app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Ruby_Assignments/Day_11/blog/app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

Ruby_Assignments/Day_11/blog/app/views/articles/index.html.erb
<h1>Articles</h1>

<ul>
  <% @articles.each do |article| %>
    <li>
          <%= link_to article.title, article %>
    </li>
  <% end %>
</ul>

<%= link_to "New Article", new_article_path %>

Ruby_Assignments/Day_11/blog/app/views/articles/new.html.erb
<h1>New Article</h1>
<%= render "form", article: @article %>

Ruby_Assignments/Day_11/blog/app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.body %></p>

<ul>
  <% if model_signed_in? %>
    <li><%= link_to "Edit", edit_article_path(@article)%></li>
  <% end %>
  <li><%= link_to "Destroy", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

Ruby_Assignments/Day_11/blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>

  <div class="container">
  <body >


      <div class="row justify-content-start">
        <div class="col-4">

        </div>
    </div>

    <% if model_signed_in? %>
      Welcome
    <%= current_model.email%>
    <%= link_to "Sign_out", destroy_model_session_path, data: {turbo_method: :delete} %>
    <%else%>
    <%= link_to "Sign_in", model_session_path %>
    <%end%>

    <div class="row justify-content-start">
     <div class="col-4">
       <%= yield %>

   </div>

   </br></br></br>
  </body>
</div>


<div class="row justify-content-start">
  <div class="col-4">

  </div>
</html>